AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API - usf.sdlc::dod
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  DodFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: usf.sdlc.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://sdlc-lambda-dev/9113d030edd1ab46d00c0c155a41382c
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 29
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  DevApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping
    Export:
      Name: DevApi
