AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API - usf.sdlc::dod
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  DodFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: usf.sdlc.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/exploded
      MemorySize: 320
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MyServiceApi