name: Producation Action

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          EXPO_CLIENT_ID: ${{ secrets.EXPO_CLIENT_ID }}
          ANDROID_CLIENT_ID: ${{ secrets.ANDROID_CLIENT_ID }}
          HIBERNATE_SHOW_SQL: ${{ secrets.HIBERNATE_SHOW_SQL }}
