name: Java CI

on:
  push:
    branches: 
      - 'hiepbp_dev'
      - 'master'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  deploy:
    needs: [build]
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build the Docker image
      run: docker build . -t dod-functions
    - name: This extracts the function.zip file built by the docker container to the build/ directory
      run: mkdir build && docker run --rm --entrypoint cat dod-functions  /home/application/function.zip > build/function.zip
    - name: List build folder
      run: ls ./build
    - name: Deploy to AWS lambda function
      uses: appleboy/lambda-action@v0.0.2
      with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: dod-functions
          zip_file: build/function.zip
